name: Test Build

on: push

jobs:
  build-uno:
    steps:
        - uses: actions/checkout@v1
        - name: Build all example sketches
          uses: Legion2/arduino-builder-action@v2.0.0
          with:
            board: "arduino:avr:uno"
  build-mega:
    steps:
        - uses: actions/checkout@v1
        - name: Build all example sketches
          uses: Legion2/arduino-builder-action@v2.0.0
          with:
            board: "arduino:avr:mega"
